### ISSUE TITLE
Missing 'Search' documentation page

### ISSUE THREAD

**Issue by kvalade** [mautic/documentation#109]
In section 4.1, there is a line: "You can learn more about the powerful search options available on the search documentation page."

However, I can't find a search documentation page. Does this exist?

**Comment by funkolector** [comment]
+1

**Comment by fisipjm** [comment]
+1 Push

**Comment by killboard** [comment]
still missing

**Comment by RCheesley** [comment]
I'm going to work on this

**Comment by fantleas** [comment]
I also want to learn the advanced search features but the documentation is missing.

**Comment by escopecz** [comment]
@RCheesley created this page recently: https://www.mautic.org/docs/en/search/index.html

Is there still something missing?
