### ISSUE TITLE
Contact Monitoring Markdown Formatting Awry

### ISSUE THREAD

**Issue by jordan8037310** [mautic/documentation#110]
Certain sections are being formatted as code blocks, when really they should be broken up into smaller pieces.

There is likely a missing triple-tick ```, and once that is addressed everything will be fixed.

![image](https://cloud.githubusercontent.com/assets/3300713/19207094/9973a676-8ca2-11e6-9433-df5eb6c3529e.png)

**Comment by kvalade** [comment]
I'll try to tackle this.

**Comment by jordan8037310** [comment]
This is fixed with the merge 10 days ago.
