### ISSUE TITLE
Relative paths for images

### ISSUE THREAD

**Issue by isleshocky77** [mautic/documentation#132]
I had made a pull request (#131) to correct the image notation in the docs for the Salesforce plugin so that it would display on github as well (I believe) on the docs website.

However, after reading the first page of the docs I see that it is recommended that the image paths are absolute root relative (i.e. "/plugin/media/image.png").

For linking between pages it is recommended to do relative paths (i.e. "./../plugin/page2.html)

The latter works on github as well, why are the images done with absolute paths? Can we change this so images are displayed on the docs page as well as in github and people's local machines (clone'd code)?

**Comment by virgilwashere** [comment]
Yes!

The new [CONTRIBUTING](/mautic/documentation/CONTRIBUTING.md) document (#351) will address this today.

**Comment by virgilwashere** [comment]
This branch is updating documentation to use relative images:

https://github.com/virgilwashere/mautic-documentation/tree/virgilwashere-relative-images
