### ISSUE TITLE
Elastic Email integration documentation disappear

### ISSUE THREAD

**Issue by kuzmany** [mautic/documentation#145]
This PR was merged but doesn't show in documentation https://github.com/mautic/documentation/pull/126

**Comment by RCheesley** [comment]
https://github.com/mautic/documentation/commit/2a46dd16ea98fbf41a9a22b8e549878eaa86a71b#diff-e75fb246c17ec91f37861dccb8d751bf it was moved to a more appropriate location, closing this old issue :)
