### ISSUE TITLE
Cron > Tips & Troubleshooting

### ISSUE THREAD

**Issue by moltar** [mautic/documentation#169]
Under "Tips & Troubleshooting" section, there is an example of how to pipe cron output to a file:

> To assist in troubleshooting cron issues, you can pipe the output of each cron job to a specific file by adding something like `>/path/to/somefile.log 2>&1` at the end of the cron job. 

But this would overwrite the log on every cron run, which isn't too useful. Better to use `>>` to append log.

**Comment by escopecz** [comment]
Thanks for pointing it out! Would you be able to [update the docs](https://github.com/mautic/documentation#how-to-contribute-to-the-docs)?

**Comment by moltar** [comment]
Done.
