### ISSUE TITLE
Wrong command in bounce processing

### ISSUE THREAD

**Issue by dsonnet** [mautic/documentation#178]
Cron command for processing bounced mails is written like this in the doc

php app/console mautic:fetch:email

While correct version is 

php app/console mautic:email:fetch

**Comment by escopecz** [comment]
Thanks for pointing it out! Do you think you'll be able to submit the fix? https://github.com/mautic/documentation#how-to-contribute-to-the-docs

**Comment by dsonnet** [comment]
I just did it, could you cofirm it is ok 3 pull requests for all the languages

**Comment by escopecz** [comment]
All are merged. Thanks!
