### ISSUE TITLE
WebhookQueueEvent class returning wrong objects for "getWebhookQueue" and "getWebhook" methods

### ISSUE THREAD

**Issue by hafeezhameed** [mautic/documentation#264]
The app/bundles/WebhookBundle/Event/WebhookQueueEvent.php class' "getWebhookQueue()" method is returning $this->getWebhookQueue() which should be returning $this->entity and "getWebhook()" method is returning $this->getWebhook() which should be returning $this->webhook;

Please fix this issue as it is throwing errors recursively. Thanks

**Comment by escopecz** [comment]
Can you link where it is in the documentation?

**Comment by RCheesley** [comment]
Closing as this is not an issue with the documentation
