### ISSUE TITLE
p Font size of Japanese version is now very small

### ISSUE THREAD

**Issue by katzueno** [mautic/documentation#272]
I now realized that Japanese font size is very small.

![image](https://user-images.githubusercontent.com/485751/39225091-62795ddc-4885-11e8-9678-7562297251e5.png)

I've notoced that

If we remove

```
p {
    font-size: 1rem;
}
```

from CSS, it will solve the issue.
However, I cannot seem to find where this CSS was set.

It could be coming from Mautic WordPress Theme, and messing up the CSS file?

**Comment by RCheesley** [comment]
Closing as no longer relevant
