### ISSUE TITLE
Confusing list tag (CSS)

### ISSUE THREAD

**Issue by katzueno** [mautic/documentation#273]
This may be related to #272 

List tag CSS is not really well-balanced.
https://www.mautic.org/docs/en/emails/troubleshooting.html

![image](https://user-images.githubusercontent.com/485751/39228966-9b0661ac-489b-11e8-94d2-c010d8a117b1.png)

It's hard to see which is new list items.

**Comment by RCheesley** [comment]
Completely agree with this, I believe it's due to the Gitbook CSS which brings in some interesting styling! I'll see what we can do!
