### ISSUE TITLE
needs CI to validate rendering to web

### ISSUE THREAD

**Issue by aspiers** [mautic/documentation#311]
This repository contains both `.travis.yml` and `appveyor.yml`, but no CI build jobs are visible on any of the PRs.  It's important that contributors are able to validate how their proposed changes in PRs render to HTML, to check that they will look right on the website when merged.  Ideally there would be a CI job which outputs the rendered version as viewable artifacts.

**Comment by RCheesley** [comment]
Closing this down as it's not relevant now we have the new docs portal :+1:
