### ISSUE TITLE
campaign builder havn't *Send Text Message* action option

### ISSUE THREAD

**Issue by nirajvara** [mautic/documentation#376]
Hi

I want to Set the text message in mautic v2.16.0 . I have set the Twilio account details also. After that as per the document below, I went to the Campaigns --> and open the campaign builder but I didn't find any option like   *Send Text Message* action  see below screenshot

1. Go to *Campaigns*.
2. Edit an existing campaign or create a new one.
3. Open the Campaign Builder.
4. Add a *Send Text Message* action to the canvas.

![image](https://user-images.githubusercontent.com/20708475/75326434-a08f9f00-58a0-11ea-8278-fa089b6c9fb9.png)

Please guide how I get this option.

**Comment by RCheesley** [comment]
Hi @nirajvara and thanks for your issue. 

I'd suggest taking a look at the documentation for how to use the campaign builder: https://www.mautic.org/docs/en/campaigns/campaign_builder.html

The 'send text message' option comes up as an Action, once you have decided where your campaign starts (segment or form). So you need to create the campaign and get to the action step before you'll see the action of 'send text message'.

**Comment by nirajvara** [comment]
thanks
