### ISSUE TITLE
UPDATE HAS CREATED AN ERROR AND I HAVE NOT BEEN ABLE TO FIX IT.

### ISSUE THREAD

**Issue by bratyboby** [mautic/documentation#378]
I have made the update to the date of today and once updated from the option of the same mautic panel, having waited 24 Hours with the pending update circle that never ended and once refreshed the page was updated but left as an error not being able to access https://mautic.mywebpage.com/s/config/edit page
and since I cannot access that page, I am in serious trouble, I have looked for opinions on the internet and they tell me to delete the cache folder var / cache and it does not allow me to delete it, I do not understand why someone could help me?

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
