### ISSUE TITLE
There is no folder called `app/cache` in Mautic mention in getting started document

### ISSUE THREAD

**Issue by AvinashDalvi89** [mautic/documentation#379]
While installation of Mautic found one issue is mentioned on getting started with Mautic documentation. 
https://docs.mautic.org/en/setup/getting-started. As I know only `var/cache` folder exist, there no existence of folder `app/cache`. 
![Screen Shot 2021-06-08 at 1 11 42 AM](https://user-images.githubusercontent.com/3996105/121078388-87410680-c7f6-11eb-8aca-fab6f8459187.png)

Correct document reference : https://docs.mautic.org/en/troubleshooting/file-ownership-and-permissions
![Screen Shot 2021-06-08 at 1 12 58 AM](https://user-images.githubusercontent.com/3996105/121078505-ad66a680-c7f6-11eb-82d7-62610c1144d9.png)

Fixed for this change text from `app/cache` to `var/cache`

**Comment by RCheesley** [comment]
Please use https://github.com/mautic/mautic-documentation as this repo has been deprecated for some years!
