### ISSUE TITLE
Incorrect PDF documentation link

### ISSUE THREAD

**Issue by ioncube** [mautic/documentation#50]
The link "Click here to download these docs as a PDF." https://mautic.org/docs/mautic_docs.pdf in the "Download as PDF" section is invalid.

**Comment by imrodmartin** [comment]
this has been corrected.  thanks!  https://mautic.org/docs/mautic_docs_en.pdf

**Comment by rbaffoe** [comment]
Reopening this issue. Link is invalid

**Comment by realitygaps** [comment]
Link is still invalid. Surely this is an easy fix?

**Comment by mikedambrogia** [comment]
link is still invalid

**Comment by alanhartless** [comment]
Thanks. There was an error in the hook that auto-built the docs after a documentation PR was merged. I've fixed it so should be good going forward now.
