### ISSUE TITLE
Section navigation prevents copy/paste by drag on Chrome

### ISSUE THREAD

**Issue by ioncube** [mautic/documentation#51]
The previous and next navigation regions on pages overlap the help text body, as seen in the image. On Chrome this prevents copying a line if the cursor enters the navigation region. Triple clicking or clicking above the text to be selected and dragging outside of the region does work. Increasing the max-width of the content and the navigation controls, or narrowing the overlapping region should resolve. 

![mautic-help-overlap-issue](https://cloud.githubusercontent.com/assets/1902741/14940871/62c770c6-0f7f-11e6-9160-2875b6de2315.png)

**Comment by phylophyl** [comment]
work around: reduce the width of the page to be able to copy your block of text.

**Comment by RCheesley** [comment]
Closing this as we have a new platform now which resolves this issue! Hurrah! :tada:
