### ISSUE TITLE
'addLead' variables order is $listId, $leadId. Not the other way around.

### ISSUE THREAD

**Issue by iadj** [mautic/documentation#60]
The documentation says:
`$listApi->addLead($leadId, $listId);`

Should be:
`$listApi->addLead($listId, $leadId);`

**Comment by escopecz** [comment]
@iadj could you please contribute this fix yourself? https://github.com/mautic/documentation#how-to-contribute-to-the-docs

**Comment by jordan8037310** [comment]
Bumping this issue and PR for review
