### ISSUE TITLE
Possible wrong command in 'Cron Jobs' chapter

### ISSUE THREAD

**Issue by sroukens** [mautic/documentation#7]
It seems that one of the cron commands in the chapter 'Cron Jobs' is not correct.
On that manual page of 'Cron Jobs' (beneath the 'To execute campaigns events:') it says: "php /path/to/mautic/app/console mautic:campaigns:update --env=prod" but I think it should be "php /path/to/mautic/app/console mautic:campaigns:trigger --env=prod". I'm not shure if I'm correct or not.

**Comment by escopecz** [comment]
Yes, that is fixed for some time. Closing this issue.
