### ISSUE TITLE
Doc menu similar to Mautic admin

### ISSUE THREAD

**Issue by phylophyl** [mautic/documentation#81]
Proposition before pull request. Documentation's menu should be similar to Mautic administration interface to be user friendly. New Menu design accordingly:
1. Overview (add + text)
2. DashBorad
3. Calendar (add  + text)
4. Contacts
5. Segments (add + text)
6. Components
7. Campaigns (up)
8. Channels (down)
9. Points
10. Stages (add  + text)
11. Reports (down)

**Comment by RCheesley** [comment]
This has been actioned in the new docs portal at https://docs.mautic.org so closing this down now.
