### ISSUE TITLE
Contact stage doc is missing

### ISSUE THREAD

**Issue by npracht** [mautic/documentation#88]
Hi,

It seems that contact stage management mautic/mautic#1770 is a great feature. But it's hard to correctly use without a documentation. Could someone (@mqueme ?) write this?
Thanks for help,

N.

**Comment by HermanMonteiro** [comment]
Friend, there is a group on facebook that maybe someone can guide you about this question. If you want to add any group.

**Comment by RCheesley** [comment]
Stages are documented here: https://www.mautic.org/docs/en/stages/stages.html
