### ISSUE TITLE
Social Monitoring on Cron Documentation

### ISSUE THREAD

**Issue by jordan8037310** [mautic/documentation#89]
Social Monitoring Cron Job is not listed on the Cron Documentation page.

e.g. `*/5 * * * * /usr/bin/php /www/app/console mautic:social:monitoring --env=prod`

**Comment by escopecz** [comment]
Thanks! If you'd like to contribute it yourself, here's how: https://github.com/mautic/documentation#how-to-contribute-to-the-docs

**Comment by escopecz** [comment]
Ah, you already did. I'll close this issue then.
